###
### appveyor.yml
###

## General configuration
version: '{build}'
skip_commits:
  message: /\[ci\s+skip\]/

## Environment configuration
shallow_clone: true
clone_depth: 1
environment:
  matrix:
    - nodejs_version: '10'
    - nodejs_version: '8'
matrix:
  fast_finish: true
install:
  ## Node-related installs
  - ps: Add-AppveyorMessage "Installing Node..."
  - set PATH=%APPDATA%\npm;C:\MinGW\bin;%PATH%
  - ps: Install-Product node $env:nodejs_version x64
  - ps: Add-AppveyorMessage "Installing npm..."
  - npm install -g npm
  ## GTK
  - ps: Add-AppveyorMessage "Installing GTK2..."
  - appveyor DownloadFile "http://ftp.gnome.org/pub/GNOME/binaries/win64/gtk+/2.22/gtk+-bundle_2.22.1-20101229_win64.zip" -FileName gtk2.zip
  - 7z x gtk2.zip -oC:\GTK
  ## Mocha-related package installs
  - ps: Add-AppveyorMessage "Installing Mocha dependencies..."
  - npm ci --ignore-scripts

## Build configuration
platform:
  - x64
build: script
build_script:
  - ps: Add-AppveyorMessage "Verify Growl responding..."

## Test configuration
before_test:
  - set CI=true
test_script:
  - ps: Add-AppveyorMessage "Displaying version information"
  - ps: (Get-ComputerInfo -Property OsName,OsVersion,OsArchitecture | Format-Table -HideTableHeaders -AutoSize | Out-String).Trim()
  - node --version
  - npm --version
  - ps: Add-AppveyorMessage "Print variables"
  - node print.js
  - ps: Add-AppveyorMessage "Making docs..."
  - npm start docs
  - ps: Add-AppveyorMessage "Done"

